Ase basic training
# part1  numpy array

In [8]:
import numpy as np
a = np.zeros((2,3))
a[:,1]=3
a[1] = 5
print(a)

print(a.shape)
print(a.ndim)

[[0. 3. 0.]
 [5. 5. 5.]]
(2, 3)
2


In [16]:
#linear algebra
import numpy as np
#make a random hermitian matrix, H
H = np.random.rand(6,6) + 1.j*np.random.rand(6,6)
H =  H + H.T.conj()
print(H)
H.shape

[[1.85662816+0.j         0.66507389+0.54858653j 1.3928461 -0.2081123j
  0.3939532 -0.10921454j 1.70544004-0.25426471j 0.92525921-0.28207304j]
 [0.66507389-0.54858653j 0.91330313+0.j         1.21174528+0.38333084j
  1.69638416+0.54702698j 1.61988342+0.17598066j 0.93304477-0.03955236j]
 [1.3928461 +0.2081123j  1.21174528-0.38333084j 0.72807478+0.j
  0.57622579+0.47843793j 0.42850745+0.38087669j 0.66977785+0.63311175j]
 [0.3939532 +0.10921454j 1.69638416-0.54702698j 0.57622579-0.47843793j
  1.38553087+0.j         0.9374565 +0.62725513j 1.2994219 -0.21258067j]
 [1.70544004+0.25426471j 1.61988342-0.17598066j 0.42850745-0.38087669j
  0.9374565 -0.62725513j 1.54741104+0.j         0.6117725 -0.34906404j]
 [0.92525921+0.28207304j 0.93304477+0.03955236j 0.66977785-0.63311175j
  1.2994219 +0.21258067j 0.6117725 +0.34906404j 1.11908201+0.j        ]]


(6, 6)

In [23]:
# Determine eigenvalues and rotation matrix
eps,U =np.linalg.eigh(H)
print("eigenvalue:" + str(eps))
print("rotation matrix:"+str(U) )
U.shape

eigenvalue:[-1.75334211 -0.55152006  0.1516007   1.08166545  2.14674948  6.47487653]
rotation matrix:[[-0.37100912+0.j          0.38336116+0.j          0.17829395+0.j
   0.30598561+0.j         -0.63533527+0.j         -0.43164756+0.j        ]
 [-0.37208119-0.51496068j -0.26084292-0.08361282j  0.1036072 +0.00157204j
  -0.48366213-0.10884254j  0.1516357 +0.22561133j -0.43510533-0.0402217j ]
 [ 0.47896013+0.02830423j -0.22257994-0.00772861j  0.32244177-0.41772484j
   0.01815351+0.53558277j -0.10014118+0.18684465j -0.31590525-0.09908584j]
 [ 0.21994356+0.09257434j  0.68117234+0.01566311j  0.06825764+0.04980813j
  -0.09853628-0.04218984j  0.535202  -0.05261092j -0.41348437+0.00244478j]
 [ 0.23809641+0.30041465j -0.21704313+0.1468386j  -0.55288493-0.06495312j
  -0.2748762 -0.23509389j -0.24837396-0.2649213j  -0.45505947+0.06865182j]
 [ 0.0085108 +0.15672556j -0.3941266 -0.20039054j  0.02520547+0.60111204j
   0.47532951+0.07186802j  0.2365495 +0.02187174j -0.35816416-0.0456373j ]]


(6, 6)

In [44]:
M = np.arange(2,32).reshape(5,6)
print(M)
v5= np.arange(5)
v5c =v5[:,None] #column vector
v5r = v5[None,:]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)
   

[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]
 [26 27 28 29 30 31]]
[[ 4  6  8 10 12 14]
 [16 18 20 22 24 26]
 [28 30 32 34 36 38]
 [40 42 44 46 48 50]
 [52 54 56 58 60 62]]
17


In [65]:
# an ase example
from  ase import Atoms
from ase.build import fcc111,add_adsorbate
from ase.visualize import view
from ase.calculators.emt import  EMT
d= 1.10
molecule = Atoms('2N',positions=[(0,0,0),(0,0,d)])
slab= fcc111('Cu',size=(4,4,2),vacuum=10)


#attach a calculator to object
slab.calc = EMT()
molecule.calc = EMT()



#add N2 to the copper slab
h=1.85
add_adsorbate(slab,molecule,h,"ontop")

# relexation of structure
#fix slab, only move molecule
from ase.constraints import FixAtoms
constraint =FixAtoms(mask=[a.symbol != "N" for a in slab])
slab.set_constraint(constraint)

#quasinewton minimizer  optimizer
from ase.optimize import QuasiNewton
dyn = QuasiNewton(slab)
dyn.run(fmax= 0.05)

#calculate the potential

e_slab = slab.get_potential_energy()
e_N2 = molecule.get_potential_energy()

print(e_slab)
view(slab)

                Step[ FC]     Time          Energy          fmax
*Force-consistent energies used in optimization.
BFGSLineSearch:    0[  0] 14:55:36       11.689927*       1.0797
BFGSLineSearch:    1[  2] 14:55:36       11.670814*       0.4090
BFGSLineSearch:    2[  4] 14:55:36       11.625880*       0.0409
11.625880434287865


<Popen: returncode: None args: ['/Users/dell/anaconda3/envs/ase/bin/python',...>

In [71]:
#ase files
from ase.io import write
write('slab.traj',slab)

OSError: [Errno 30] Read-only file system: 'slab.traj'